# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hello world Cpp
#'
#' Hello world function Cpp
#'
#' @return None
#'
#' @examples
#' rcpp_hello()
#'
#' @export
rcpp_hello <- function() {
    .Call(`_rMSIcleanup_rcpp_hello`)
}

